import {beforeEach,describe,it,expect,vi} from 'vitest';
vi.mock('server-only',()=>({}));
const m=vi.hoisted(()=>({auth:vi.fn(),tx:{$queryRaw:vi.fn(),user:{findUnique:vi.fn()},dailyTask:{findFirst:vi.fn(),update:vi.fn()},dailyTaskUpdate:{upsert:vi.fn()},taskActivityEvent:{aggregate:vi.fn(),create:vi.fn()},taskTimelineEntry:{create:vi.fn()},managementAuditLog:{create:vi.fn()},reportEditRequest:{findFirst:vi.fn(),create:vi.fn(),update:vi.fn()}}}));
vi.mock('@/lib/auth/server',()=>({getServerAuthContext:m.auth}));
vi.mock('@/lib/db',()=>({db:{$transaction:async(fn:(tx:typeof m.tx)=>Promise<unknown>)=>fn(m.tx)}}));
import {taskLifecycle} from './task-lifecycle';
import {saveTaskPlanning} from './task-planning';
import {savePersonalReport} from './report-actions';
const id='11111111-1111-4111-8111-111111111111',actor={id:'self',role:'employee',isActive:true,managementEnabled:false,permissions:[],accessScopes:[]};
const day='2026-09-13';
function task(overrides:Record<string,unknown>={}){return {id,userId:'self',taskTitle:'Example work',taskDescription:'Description',planDate:new Date(day),assignedBy:null,checklist:[],planningVersion:0,projectName:null,clientName:null,dueAt:null,estimatedMinutes:null,updates:[],...overrides};}
function req(body:unknown){return new Request(`http://localhost:3000/api/dashboard/tasks/${id}`,{method:'POST',headers:{origin:'http://localhost:3000','content-type':'application/json'},body:JSON.stringify(body)});}
beforeEach(()=>{vi.clearAllMocks();vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-13T12:00:00Z'));m.auth.mockResolvedValue({user:actor});m.tx.user.findUnique.mockResolvedValue(actor);m.tx.dailyTask.findFirst.mockResolvedValue(task());m.tx.dailyTask.update.mockResolvedValue({...task(),planningVersion:1});m.tx.taskActivityEvent.aggregate.mockResolvedValue({_max:{cycle:null}});});
describe('Completion/reopen invariants',()=>{
 it('rejects anonymous writes before opening a transaction',async()=>{m.auth.mockResolvedValue({user:null});expect((await taskLifecycle(req({action:'complete_task'}),id)).status).toBe(401);expect(m.tx.$queryRaw).not.toHaveBeenCalled();});
 it('rejects cross-origin writes',async()=>{const r=new Request('http://localhost:3000/api',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'});expect((await taskLifecycle(r,id)).status).toBe(403);});
 it('never trusts a task ID outside the owner scope',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(null);expect((await taskLifecycle(req({action:'complete_task'}),id)).status).toBe(404);expect(m.tx.dailyTask.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id,userId:'self'}}));expect(m.tx.dailyTaskUpdate.upsert).not.toHaveBeenCalled();});
 it('Done always saves 100% and an immutable completion event',async()=>{expect((await taskLifecycle(req({action:'complete_task',completionNote:'Ready'}),id)).status).toBe(200);expect(m.tx.dailyTaskUpdate.upsert).toHaveBeenCalledWith(expect.objectContaining({update:expect.objectContaining({status:'done',completionPercent:100})}));expect(m.tx.taskActivityEvent.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({eventType:'completed',cycle:1})}));});
 it('rejects partial completion instead of silently treating it as done',async()=>{expect((await taskLifecycle(req({action:'complete_task',completionStatus:'partial'}),id)).status).toBe(400);expect(m.tx.dailyTaskUpdate.upsert).not.toHaveBeenCalled();});
 it('blocks Done when a checklist item is incomplete',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({checklist:[{id,title:'Review',done:false}]}));expect((await taskLifecycle(req({action:'complete_task'}),id)).status).toBe(409);expect(m.tx.taskActivityEvent.create).not.toHaveBeenCalled();});
 it('makes a repeated completion retry-safe',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({updates:[{reportDate:new Date(day),status:'done'}]}));expect((await taskLifecycle(req({action:'complete_task'}),id)).status).toBe(200);expect(m.tx.taskActivityEvent.create).not.toHaveBeenCalled();});
 it('increments the maximum completion cycle, not the number of rows',async()=>{m.tx.taskActivityEvent.aggregate.mockResolvedValue({_max:{cycle:9}});await taskLifecycle(req({action:'complete_task'}),id);expect(m.tx.taskActivityEvent.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({cycle:10})}));});
 it('requires a meaningful reopen reason',async()=>expect((await taskLifecycle(req({action:'reopen_task',reopenReason:'no'}),id)).status).toBe(400));
 it('preserves legacy completion before reopening on a new day',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({updates:[{id:'update',status:'done',reportDate:new Date('2026-09-12'),trackedMinutes:45,actualStart:new Date('2026-09-12T05:00:00Z'),actualEnd:new Date('2026-09-12T06:00:00Z'),updatedAt:new Date('2026-09-12T06:00:00Z'),note:'Old completion'}]}));expect((await taskLifecycle(req({action:'reopen_task',reopenReason:'Additional testing is needed'}),id)).status).toBe(200);expect(m.tx.taskActivityEvent.create.mock.calls[0][0].data).toMatchObject({eventType:'completed',trackedMinutes:45,note:'Old completion'});expect(m.tx.dailyTaskUpdate.upsert).toHaveBeenCalledWith(expect.objectContaining({update:expect.objectContaining({trackedMinutes:0,actualStart:null,actualEnd:null,status:'in_progress'})}));});
 it('management reopen requires a scoped explicit grant',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(null);expect((await taskLifecycle(req({reason:'Additional testing required'}),id,true)).status).toBe(404);expect(m.tx.dailyTask.findFirst.mock.calls[0][0].where.user).toEqual({id:{in:[]}});});
 it('re-checks active account state inside the transaction',async()=>{m.tx.user.findUnique.mockResolvedValue({...actor,isActive:false});expect((await taskLifecycle(req({action:'complete_task'}),id)).status).toBe(403);expect(m.tx.dailyTaskUpdate.upsert).not.toHaveBeenCalled();});
});
describe('Planning controls',()=>{
 const input={version:0,projectName:null,clientName:null,dueAt:null,estimatedMinutes:null,checklist:[]};
 it('rejects stale versions',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({planningVersion:1}));expect((await saveTaskPlanning(req(input),id)).status).toBe(409);});
 it('rejects edits to completed records',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({updates:[{status:'done'}]}));expect((await saveTaskPlanning(req(input),id)).status).toBe(409);});
 it('does not let an assignee change a managers deadline',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({assignedBy:'manager'}));expect((await saveTaskPlanning(req({...input,dueAt:'2026-09-15T12:00:00Z'}),id)).status).toBe(403);});
 it('lets an assignee check off an existing item',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({assignedBy:'manager',checklist:[{id,title:'Review',done:false}]}));expect((await saveTaskPlanning(req({...input,checklist:[{id,title:'Review',done:true}]}),id)).status).toBe(200);expect(m.tx.taskTimelineEntry.create).toHaveBeenCalled();});
 it('cannot replace checklist structure on an assigned task',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({assignedBy:'manager',checklist:[{id,title:'Review',done:false}]}));expect((await saveTaskPlanning(req(input),id)).status).toBe(403);});
});
describe('Report write guards',()=>{
 const update={dailyTaskId:id,status:'in_progress',completionPercent:60,trackedMinutes:0,actualStart:'2026-09-13T12:00:00Z'};
 it('prevents report saves from undoing completion',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({updates:[{status:'done',reportDate:new Date(day)}]}));expect((await savePersonalReport(req({reportDate:day,updates:[update]}))).status).toBe(409);});
 it('rejects historical rewrites',async()=>expect((await savePersonalReport(req({reportDate:'2026-09-12',updates:[update]}))).status).toBe(409));
 it('ignores caller-invented progress percentages',async()=>{expect((await savePersonalReport(req({reportDate:day,updates:[update]}))).status).toBe(200);expect(m.tx.dailyTaskUpdate.upsert.mock.calls[0][0].update.completionPercent).toBe(0);});
 it('rejects impossible tracked time',async()=>expect((await savePersonalReport(req({reportDate:day,updates:[{...update,trackedMinutes:600}]}))).status).toBe(400));
 it('locks task IDs in stable order to avoid cross-batch deadlocks',async()=>{const second='22222222-2222-4222-8222-222222222222';await savePersonalReport(req({reportDate:day,updates:[{...update,dailyTaskId:second},update]}));expect(m.tx.$queryRaw.mock.calls.map(c=>c[1])).toEqual([id,second]);});
});

describe('Lifecycle response contract',()=>{
 it('returns the saved completion state for every client surface',async()=>{const response=await taskLifecycle(req({action:'complete_task',completionNote:'Checked carefully'}),id);expect(response.status).toBe(200);expect((await response.json()).taskUpdate).toMatchObject({reportDate:day,status:'done',trackedMinutes:0,actualStart:null,actualEnd:'2026-09-13T12:00:00.000Z',note:'Checked carefully'});});
 it('returns a paused same-day reopen without losing previous time',async()=>{m.tx.dailyTask.findFirst.mockResolvedValue(task({updates:[{status:'done',reportDate:new Date(day),trackedMinutes:15,actualStart:new Date('2026-09-13T05:00:00Z'),actualEnd:new Date('2026-09-13T05:15:00Z'),note:'Completed'}]}));m.tx.taskActivityEvent.aggregate.mockResolvedValue({_max:{cycle:1}});const response=await taskLifecycle(req({action:'reopen_task',reopenReason:'Additional testing required'}),id);expect(response.status).toBe(200);expect((await response.json()).taskUpdate).toMatchObject({reportDate:day,status:'in_progress',trackedMinutes:15,actualStart:'2026-09-13T05:00:00.000Z',actualEnd:'2026-09-13T05:15:00.000Z'});});
});
