"use client";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { APP_ROLES, roleUiTitle, type AppRole } from "@/lib/auth/roles";
import { PERMISSIONS, READ_PERMISSIONS, SCOPE_TYPES, type Permission } from "@/lib/auth/policy";

type Person={id:string;name:string;email:string;role:AppRole;isActive:boolean;departmentId:string|null;teamId:string|null;managementEnabled:boolean;accessVersion:number;permissions:{permissionKey:string;isGranted:boolean}[];accessScopes:{scopeType:string;departmentId:string|null;teamId:string|null}[]};
type Option={id:string;name:string};
type Team=Option&{departmentId:string;leadId:string|null;members?:{id:string}[]};
const field="w-full rounded-lg border border-[var(--panel-border)] bg-[var(--panel)] px-3 py-2 text-sm";
const button="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
export function AccessControl(){
 const [users,setUsers]=useState<Person[]>([]),[departments,setDepartments]=useState<Option[]>([]),[teams,setTeams]=useState<Team[]>([]);
 const [selected,setSelected]=useState<Person|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [permissions,setPermissions]=useState<Permission[]>([]),[scope,setScope]=useState<string>('self'),[scopeIds,setScopeIds]=useState<string[]>([]),[reason,setReason]=useState('');
 const [teamDraft,setTeamDraft]=useState({id:'',name:'',departmentId:'',leadId:'',memberIds:[] as string[],reason:''});
 async function load(q='') {setLoading(true);try{const res=await fetch('/api/management/access?q='+encodeURIComponent(q),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.message);setUsers(data.users);setDepartments(data.departments);setTeams(data.teams);}catch(e){toast.error(e instanceof Error?e.message:'Could not load access.');}finally{setLoading(false);}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return ()=>clearTimeout(timer);},[]);
 function select(user:Person){setSelected({...user});setPermissions(user.permissions.filter(p=>p.isGranted).map(p=>p.permissionKey as Permission));setScope(user.accessScopes[0]?.scopeType??'self');setScopeIds(user.accessScopes.flatMap(s=>s.departmentId?[s.departmentId]:s.teamId?[s.teamId]:[]));setReason('');}
 async function save(){if(!selected)return;setSaving(true);try{
  const response=await fetch('/api/management/access',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:selected.id,role:selected.role,isActive:selected.isActive,managementEnabled:selected.managementEnabled,departmentId:selected.departmentId,teamId:selected.teamId,version:selected.accessVersion,permissions,scopeType:scope,scopeIds,reason})});const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success(data.message);setSelected(null);await load(query);
 }catch(e){toast.error(e instanceof Error?e.message:'Unable to save.');}finally{setSaving(false);}}
 async function saveTeam(){setSaving(true);try{const res=await fetch('/api/management/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...teamDraft,id:teamDraft.id||undefined,leadId:teamDraft.leadId||null})});const data=await res.json();if(!res.ok)throw new Error(data.message);toast.success(data.message);await load(query);setTeamDraft({id:'',name:'',departmentId:'',leadId:'',memberIds:[],reason:''});}catch(e){toast.error(e instanceof Error?e.message:'Unable to save team.');}finally{setSaving(false);}}
 return <div className="space-y-5">
  <div><h1 className="text-2xl font-semibold">Access Control</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">Assign roles, individual management access and employee scope. Everyone keeps their personal workspace.</p></div>
  <form onSubmit={e=>{e.preventDefault();void load(query);}} className="flex gap-2"><input aria-label="Search users" className={field} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email"/><button className={button}>Search</button></form>
  <div className="grid gap-4 lg:grid-cols-[minmax(240px,1fr)_minmax(0,2fr)]">
   <section className="max-h-[640px] space-y-1 overflow-y-auto rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-2">{loading?<p className="p-4">Loading…</p>:users.length===0?<p className="p-4">No users found.</p>:users.map(u=><button type="button" key={u.id} onClick={()=>select(u)} className={`w-full rounded-lg p-3 text-left ${selected?.id===u.id?'bg-indigo-500/15 ring-1 ring-indigo-400':'hover:bg-[var(--panel-alt)]'}`}><span className="block font-semibold">{u.name}</span><span className="block text-xs text-[var(--muted-foreground)]">{roleUiTitle(u.role)} · {u.managementEnabled?'Management enabled':'Personal workspace'}</span></button>)}<p className="px-3 py-2 text-xs text-[var(--muted-foreground)]">Showing up to 200 users. Search to find more.</p></section>
   <section className="rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-5">{selected?<div className="space-y-4">
    <div><h2 className="text-lg font-semibold">{selected.name}</h2><p className="text-sm text-[var(--muted-foreground)]">{selected.email}</p></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">Role<select className={field} value={selected.role} onChange={e=>{const role=e.target.value as AppRole;setSelected({...selected,role,managementEnabled:role==='super_admin'?true:role==='employee'?false:selected.managementEnabled});if(role==='employee')setPermissions([]);}}>{APP_ROLES.map(r=><option key={r} value={r}>{roleUiTitle(r)}</option>)}</select></label>
    <label className="space-y-1 text-sm">Department<select className={field} value={selected.departmentId??''} onChange={e=>setSelected({...selected,departmentId:e.target.value||null,teamId:null})}><option value="">No department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
    <label className="space-y-1 text-sm">Team membership<select className={field} value={selected.teamId??''} onChange={e=>setSelected({...selected,teamId:e.target.value||null})}><option value="">No team</option>{teams.filter(t=>t.departmentId===selected.departmentId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.isActive} onChange={e=>setSelected({...selected,isActive:e.target.checked})}/>Account active</label></div>
    <label className="flex items-center gap-2 rounded-lg bg-indigo-500/10 p-3 font-medium"><input type="checkbox" checked={selected.managementEnabled} disabled={selected.role==='employee'||selected.role==='super_admin'} onChange={e=>{setSelected({...selected,managementEnabled:e.target.checked});if(e.target.checked&&!permissions.length)setPermissions([...READ_PERMISSIONS]);}}/>Management Dashboard access</label>
    {selected.role==='super_admin'?<p className="text-sm">Super Admin has company-wide access and controls all permissions.</p>:selected.role!=='employee'?<>
     <label className="block space-y-1 text-sm">Employee scope<select className={field} value={scope} onChange={e=>{setScope(e.target.value);setScopeIds([]);}}>{SCOPE_TYPES.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>
     {(scope==='departments'||scope==='teams')&&<div className="grid gap-2 sm:grid-cols-2">{(scope==='departments'?departments:teams).map(o=><label className="flex gap-2 text-sm" key={o.id}><input type="checkbox" checked={scopeIds.includes(o.id)} onChange={e=>setScopeIds(prev=>e.target.checked?[...prev,o.id]:prev.filter(x=>x!==o.id))}/>{o.name}</label>)}</div>}
     <div className="flex items-center justify-between"><h3 className="font-semibold">Permissions</h3><button className="text-sm text-indigo-500" type="button" onClick={()=>setPermissions([...READ_PERMISSIONS])}>Use read-only defaults</button></div>
     <div className="grid gap-2 sm:grid-cols-2">{PERMISSIONS.map(p=><label key={p} className="flex items-center gap-2 rounded-lg border border-[var(--panel-border)] p-2 text-sm"><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(prev=>e.target.checked?[...prev,p]:prev.filter(x=>x!==p))}/>{p.replaceAll('.',' · ').replaceAll('_',' ')}</label>)}</div>
     <p className="rounded-lg bg-[var(--panel-alt)] p-3 text-sm">Effective access: {selected.managementEnabled?`${permissions.length} permissions within ${scope.replaceAll('_',' ')} scope.`:'Personal workspace only. Management permissions remain inactive.'}</p>
    </>:null}
    <label className="block text-sm">Reason for change<input className={field} value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} placeholder="Required for the audit record"/></label>
    <button type="button" disabled={saving||reason.trim().length<3} className={button} onClick={()=>void save()}>{saving?'Saving…':'Save access settings'}</button>
   </div>:<p className="text-[var(--muted-foreground)]">Select a person to review their role and access.</p>}</section>
  </div>
  <section className="space-y-3 rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-5"><h2 className="text-lg font-semibold">Team setup</h2><p className="text-sm text-[var(--muted-foreground)]">Choose a Team Head and department members. Team membership controls Own Team visibility.</p>
   <div className="grid gap-3 sm:grid-cols-3"><select aria-label="Team to edit" className={field} value={teamDraft.id} onChange={async e=>{const id=e.target.value;if(!id){setTeamDraft({id:'',name:'',departmentId:'',leadId:'',memberIds:[],reason:''});return;}try{const res=await fetch('/api/management/teams');const data=await res.json();if(!res.ok)throw new Error(data.message);const t=data.teams.find((x:Team)=>x.id===id) as Team;setTeamDraft({id:t.id,name:t.name,departmentId:t.departmentId,leadId:t.leadId??'',memberIds:t.members?.map(m=>m.id)??[],reason:''});}catch(e){toast.error(e instanceof Error?e.message:'Unable to load team.');}}}><option value="">Create a new team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>
   <input aria-label="Team name" className={field} placeholder="Team name" value={teamDraft.name} onChange={e=>setTeamDraft({...teamDraft,name:e.target.value})}/><select aria-label="Team department" className={field} value={teamDraft.departmentId} onChange={e=>setTeamDraft({...teamDraft,departmentId:e.target.value,memberIds:[]})}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>
   <select aria-label="Team Head" className={field} value={teamDraft.leadId} onChange={e=>setTeamDraft({...teamDraft,leadId:e.target.value})}><option value="">No Team Head</option>{users.filter(u=>['team_head','super_admin'].includes(u.role)&&u.isActive).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div>
   <div className="flex flex-wrap gap-3">{users.filter(u=>u.departmentId===teamDraft.departmentId).map(u=><label key={u.id} className="flex gap-2 text-sm"><input type="checkbox" checked={teamDraft.memberIds.includes(u.id)} onChange={e=>setTeamDraft({...teamDraft,memberIds:e.target.checked?[...teamDraft.memberIds,u.id]:teamDraft.memberIds.filter(x=>x!==u.id)})}/>{u.name}</label>)}</div>
   <input aria-label="Team change reason" className={field} placeholder="Reason for team change" value={teamDraft.reason} onChange={e=>setTeamDraft({...teamDraft,reason:e.target.value})}/><button type="button" className={button} disabled={saving||!teamDraft.name||!teamDraft.departmentId||teamDraft.reason.trim().length<3} onClick={()=>void saveTeam()}>Save team</button>
  </section>
 </div>;
}
