"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Search, ShieldCheck, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import { APP_ROLES, roleUiTitle, type AppRole } from "@/lib/auth/roles";
import { ATTENDANCE_DETAILS_PERMISSION, PERMISSIONS, READ_PERMISSIONS, SCOPE_TYPES, canReceiveAuditPermission, type Permission } from "@/lib/auth/policy";
import styles from "./access-control.module.css";

type Person={id:string;name:string;email:string;role:AppRole;isActive:boolean;departmentId:string|null;teamId:string|null;managementEnabled:boolean;accessVersion:number;permissions:{permissionKey:string;isGranted:boolean}[];accessScopes:{scopeType:string;departmentId:string|null;teamId:string|null;employeeId:string|null;employee?:{id:string;name:string}|null}[]};
type Option={id:string;name:string};
type Team=Option&{departmentId:string;leadId:string|null;members?:{id:string}[]};
type TeamDraft={id:string;name:string;departmentId:string;leadId:string;memberIds:string[];reason:string};
const emptyTeamDraft=():TeamDraft=>({id:'',name:'',departmentId:'',leadId:'',memberIds:[],reason:''});
const teamDraftKey=(draft:TeamDraft)=>JSON.stringify({...draft,memberIds:[...draft.memberIds].sort()});
const field="w-full rounded-lg border border-[var(--panel-border)] bg-[var(--panel)] px-3 py-2 text-sm";
const button="button-force-white rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
export function AccessControl(){
 const [users,setUsers]=useState<Person[]>([]),[departments,setDepartments]=useState<Option[]>([]),[teams,setTeams]=useState<Team[]>([]);
 const [selected,setSelected]=useState<Person|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const [searchResults,setSearchResults]=useState<Person[]>([]),[resolvedQuery,setResolvedQuery]=useState(''),[searching,setSearching]=useState(false);
 const [permissions,setPermissions]=useState<Permission[]>([]),[scope,setScope]=useState<string>('self'),[scopeIds,setScopeIds]=useState<string[]>([]);
 const [teamDraft,setTeamDraft]=useState<TeamDraft>(emptyTeamDraft),[teamBaseline,setTeamBaseline]=useState<TeamDraft>(emptyTeamDraft),[teamOpen,setTeamOpen]=useState(false);
 const teamSetupRef=useRef<HTMLElement>(null);
 async function load() {setLoading(true);try{const res=await fetch('/api/management/access',{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.message);setUsers(data.users);setDepartments(data.departments);setTeams(data.teams);setResolvedQuery('');}catch(e){toast.error(e instanceof Error?e.message:'Could not load access.');}finally{setLoading(false);}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return ()=>clearTimeout(timer);},[]);
 useEffect(()=>{const normalized=query.trim().toLocaleLowerCase();if(!normalized)return;const controller=new AbortController();const timer=setTimeout(async()=>{setSearching(true);try{const res=await fetch('/api/management/access?q='+encodeURIComponent(query.trim()),{cache:'no-store',signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.message);setSearchResults(data.users);setResolvedQuery(normalized);}catch(e){if(!controller.signal.aborted)toast.error(e instanceof Error?e.message:'Could not search users.');}finally{if(!controller.signal.aborted)setSearching(false);}},220);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 const normalizedQuery=query.trim().toLocaleLowerCase();
 const localMatches=useMemo(()=>normalizedQuery?users.filter(user=>(user.name+' '+user.email).toLocaleLowerCase().includes(normalizedQuery)):users,[normalizedQuery,users]);
 const visibleUsers=normalizedQuery&&resolvedQuery===normalizedQuery?searchResults:localMatches;
 const scopePeople=useMemo(()=>[...new Map([...users,...searchResults,...(selected?.accessScopes.flatMap(item=>item.employee?[item.employee]:[])??[])].map(person=>[person.id,person])).values()],[users,searchResults,selected]);
 const teamDirty=useMemo(()=>teamDraftKey(teamDraft)!==teamDraftKey(teamBaseline),[teamDraft,teamBaseline]);
 const closeTeamSetup=useCallback(()=>{if(saving)return false;if(teamDirty&&!window.confirm('Discard the unsaved team changes?'))return false;setTeamDraft(teamBaseline);setTeamOpen(false);return true;},[saving,teamBaseline,teamDirty]);
 useEffect(()=>{if(!teamOpen)return;function handlePointerDown(event:PointerEvent){if(teamSetupRef.current?.contains(event.target as Node))return;if(!closeTeamSetup()){event.preventDefault();event.stopPropagation();}}function handleKeyDown(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();closeTeamSetup();}}document.addEventListener('pointerdown',handlePointerDown);document.addEventListener('keydown',handleKeyDown);return()=>{document.removeEventListener('pointerdown',handlePointerDown);document.removeEventListener('keydown',handleKeyDown);};},[closeTeamSetup,teamOpen]);
 function select(user:Person){setSelected({...user});setPermissions(user.permissions.filter(p=>p.isGranted&&p.permissionKey!==ATTENDANCE_DETAILS_PERMISSION&&(p.permissionKey!=='audit_logs.view'||canReceiveAuditPermission(user.role))).map(p=>p.permissionKey as Permission));setScope(user.accessScopes[0]?.scopeType??'self');setScopeIds(user.accessScopes.flatMap(s=>s.departmentId?[s.departmentId]:s.teamId?[s.teamId]:s.employeeId?[s.employeeId]:[]));}
 async function save(){if(!selected)return;setSaving(true);try{
  const response=await fetch('/api/management/access',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:selected.id,role:selected.role,isActive:selected.isActive,managementEnabled:selected.managementEnabled,departmentId:selected.departmentId,teamId:selected.teamId,version:selected.accessVersion,permissions,scopeType:scope,scopeIds})});const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success(data.message);setSelected(null);await load();
 }catch(e){toast.error(e instanceof Error?e.message:'Unable to save.');}finally{setSaving(false);}}
 async function saveTeam(){setSaving(true);try{const res=await fetch('/api/management/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...teamDraft,id:teamDraft.id||undefined,leadId:teamDraft.leadId||null})});const data=await res.json();if(!res.ok)throw new Error(data.message);toast.success(data.message);await load();const resetDraft=emptyTeamDraft();setTeamDraft(resetDraft);setTeamBaseline(resetDraft);setTeamOpen(false);}catch(e){toast.error(e instanceof Error?e.message:'Unable to save team.');}finally{setSaving(false);}}
 return <div className={styles.page} data-fit-viewport>
  <header className={styles.header}><div><h1>Access Control</h1><p>Assign roles, management access and employee scope. Personal workspace access always remains available.</p></div></header>
  <div className={styles.searchBar}><Search aria-hidden="true" size={17}/><input aria-label="Search users" autoComplete="off" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employees by name or email..."/>{query?<button type="button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>:null}<span className={styles.searchStatus} role="status">{loading?'Loading users...':searching&&normalizedQuery?'Searching...':visibleUsers.length+' result'+(visibleUsers.length===1?'':'s')}</span></div>
  <div className={styles.workspace}>
   <section className={styles.userPanel} aria-label="Employee access list">
    {loading&&!users.length?<p className={styles.listMessage}>Loading users...</p>:visibleUsers.length===0?<div className={styles.listMessage}><UsersRound aria-hidden="true" size={22}/><p>No employees match <q>{query.trim()}</q>.</p></div>:visibleUsers.map(user=><button type="button" key={user.id} onClick={()=>select(user)} className={[styles.userButton,selected?.id===user.id?styles.userButtonSelected:''].filter(Boolean).join(' ')}><strong>{user.name}</strong><span>{roleUiTitle(user.role)} / {user.managementEnabled?'Management enabled':'Personal workspace'}</span></button>)}
   </section>
   <section className={styles.editorPanel}>{selected?<div className={[styles.editorScroll,'space-y-3'].join(' ')}>
    <div><h2 className="text-lg font-semibold">{selected.name}</h2><p className="text-sm text-[var(--muted-foreground)]">{selected.email}</p></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">Role<select className={field} value={selected.role} onChange={e=>{const role=e.target.value as AppRole;setSelected({...selected,role,managementEnabled:role==='super_admin'?true:role==='employee'?false:selected.managementEnabled});setPermissions(previous=>role==='employee'?[]:previous.filter(permission=>permission!=='audit_logs.view'||canReceiveAuditPermission(role)));}}>{APP_ROLES.map(r=><option key={r} value={r}>{roleUiTitle(r)}</option>)}</select></label>
    <label className="space-y-1 text-sm">Department<select className={field} value={selected.departmentId??''} onChange={e=>setSelected({...selected,departmentId:e.target.value||null,teamId:null})}><option value="">No department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
    <label className="space-y-1 text-sm">Team membership<select className={field} value={selected.teamId??''} onChange={e=>setSelected({...selected,teamId:e.target.value||null})}><option value="">No team</option>{teams.filter(t=>t.departmentId===selected.departmentId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.isActive} onChange={e=>setSelected({...selected,isActive:e.target.checked})}/>Account active</label></div>
    <label className="flex items-center gap-2 rounded-lg bg-indigo-500/10 p-3 font-medium"><input type="checkbox" checked={selected.managementEnabled} disabled={selected.role==='employee'||selected.role==='super_admin'} onChange={e=>{setSelected({...selected,managementEnabled:e.target.checked});if(e.target.checked&&!permissions.length)setPermissions([...READ_PERMISSIONS]);}}/>Management Dashboard access</label>
    {selected.role==='super_admin'?<p className="text-sm">Super Admin has company-wide access and controls all permissions.</p>:selected.role!=='employee'?<>
     <label className="block space-y-1 text-sm">Employee scope<select className={field} value={scope} onChange={e=>{setScope(e.target.value);setScopeIds([]);}}>{SCOPE_TYPES.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>
     {(['departments','teams','employees'].includes(scope))&&<div className="grid gap-2 sm:grid-cols-2">{(scope==='departments'?departments:scope==='teams'?teams:scopePeople.filter(user=>!('isActive' in user)||user.isActive)).map(o=><label className="flex gap-2 text-sm" key={o.id}><input type="checkbox" checked={scopeIds.includes(o.id)} onChange={e=>setScopeIds(prev=>e.target.checked?[...prev,o.id]:prev.filter(x=>x!==o.id))}/>{o.name}</label>)}</div>}
     {scope==='employees'&&<p className="text-xs text-[var(--muted-foreground)]">Search by name or email above to add employees beyond the first page. Existing grants remain selected.</p>}
     <div className="flex items-center justify-between"><h3 className="font-semibold">Management permissions</h3><button className="text-sm text-indigo-500" type="button" onClick={()=>setPermissions([...READ_PERMISSIONS])}>Use read-only defaults</button></div>
     <div className="grid gap-2 sm:grid-cols-2">{PERMISSIONS.filter(permission=>permission!==ATTENDANCE_DETAILS_PERMISSION&&(permission!=='audit_logs.view'||canReceiveAuditPermission(selected.role))).map(p=><label key={p} className="flex items-center gap-2 rounded-lg border border-[var(--panel-border)] p-2 text-sm"><input type="checkbox" checked={permissions.includes(p)} onChange={e=>setPermissions(prev=>e.target.checked?[...prev,p]:prev.filter(x=>x!==p))}/>{p==='audit_logs.view'?'View Audit Log':p.replaceAll('.',' / ').replaceAll('_',' ')}</label>)}</div>
     <p className="rounded-lg bg-[var(--panel-alt)] p-3 text-sm">Effective access: {selected.managementEnabled?`${permissions.length} permissions within ${scope.replaceAll('_',' ')} scope.`:'Personal workspace only. Management permissions remain inactive.'}</p>
    </>:null}
    <button type="button" disabled={saving} className={button} onClick={()=>void save()}>{saving?'Saving…':'Save access settings'}</button>
   </div>:<div className={styles.emptyEditor}><ShieldCheck aria-hidden="true" size={30}/><strong>Select an employee</strong><p>Choose a person to review their role, scope and permissions.</p></div>}</section>
  </div>
  <section ref={teamSetupRef} className={[styles.teamSetup,teamOpen?styles.teamSetupOpen:''].filter(Boolean).join(' ')}><button type="button" className={styles.teamSummary} aria-expanded={teamOpen} aria-controls="team-setup-panel" onClick={()=>{if(teamOpen)closeTeamSetup();else setTeamOpen(true);}}><UsersRound aria-hidden="true" size={16}/><strong>Team setup</strong><span>Manage Team Heads and department members</span></button>{teamOpen?<div id="team-setup-panel" className={[styles.teamBody,'space-y-2'].join(' ')}><div className={styles.teamBodyHeader}><strong>Team configuration</strong><button type="button" className={styles.teamClose} aria-label="Close team setup" title="Close team setup" onClick={()=>closeTeamSetup()}><X aria-hidden="true" size={17}/></button></div>
   <div className={styles.teamGrid}><select aria-label="Team to edit" className={field} value={teamDraft.id} onChange={async e=>{const id=e.target.value;if(teamDirty&&!window.confirm('Discard the current changes and open another team?'))return;if(!id){const resetDraft=emptyTeamDraft();setTeamDraft(resetDraft);setTeamBaseline(resetDraft);return;}try{const res=await fetch('/api/management/teams');const data=await res.json();if(!res.ok)throw new Error(data.message);const t=data.teams.find((x:Team)=>x.id===id) as Team;const nextDraft={id:t.id,name:t.name,departmentId:t.departmentId,leadId:t.leadId??'',memberIds:t.members?.map(m=>m.id)??[],reason:''};setTeamDraft(nextDraft);setTeamBaseline(nextDraft);}catch(e){toast.error(e instanceof Error?e.message:'Unable to load team.');}}}><option value="">Create a new team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>
   <input aria-label="Team name" className={field} placeholder="Team name" value={teamDraft.name} onChange={e=>setTeamDraft({...teamDraft,name:e.target.value})}/><select aria-label="Team department" className={field} value={teamDraft.departmentId} onChange={e=>setTeamDraft({...teamDraft,departmentId:e.target.value,memberIds:[]})}><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>
   <select aria-label="Team Head" className={field} value={teamDraft.leadId} onChange={e=>setTeamDraft({...teamDraft,leadId:e.target.value})}><option value="">No Team Head</option>{users.filter(u=>['team_head','super_admin'].includes(u.role)&&u.isActive).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div>
   {teamDraft.departmentId?<div className={styles.teamMembers}>{users.filter(u=>u.departmentId===teamDraft.departmentId).map(u=><label key={u.id} className="flex gap-2 text-sm"><input type="checkbox" checked={teamDraft.memberIds.includes(u.id)} onChange={e=>setTeamDraft({...teamDraft,memberIds:e.target.checked?[...teamDraft.memberIds,u.id]:teamDraft.memberIds.filter(x=>x!==u.id)})}/>{u.name}</label>)}</div>:null}
   <div className={styles.teamActions}><input aria-label="Team change reason" className={field} placeholder="Reason for team change" value={teamDraft.reason} onChange={e=>setTeamDraft({...teamDraft,reason:e.target.value})}/><button type="button" className={button} disabled={saving||!teamDraft.name||!teamDraft.departmentId||teamDraft.reason.trim().length<3} onClick={()=>void saveTeam()}>Save team</button></div>
  </div>:null}</section>
 </div>;
}
