'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {toast} from 'sonner';
export function EmployeeProfileEditor({employee}:{employee:{id:string;name:string;designation:string|null;phone:string|null;location:string|null;updatedAt:string}}){
 const [busy,setBusy]=useState(false);const router=useRouter();
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch(`/api/management/employees/${employee.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(form),updatedAt:employee.updatedAt})});const data=await response.json();if(!response.ok)throw new Error(data.message);toast.success(data.message);router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}
 return <details className="mt-5 border-t border-[var(--panel-border)] pt-3"><summary className="cursor-pointer text-sm text-indigo-600">Edit employee profile</summary><form onSubmit={save} className="mt-3 grid gap-3 sm:grid-cols-2">{(['name','designation','phone','location'] as const).map(key=><label key={key} className="text-xs capitalize">{key}<input name={key} required={key==='name'} defaultValue={employee[key]??''} maxLength={key==='phone'?40:key==='location'?200:120} className="mt-1 block w-full rounded border border-[var(--panel-border)] bg-[var(--panel)] p-2 text-sm"/></label>)}<label className="text-xs sm:col-span-2">Reason for change<textarea required minLength={10} maxLength={1000} name="reason" className="mt-1 block w-full rounded border border-[var(--panel-border)] bg-[var(--panel)] p-2 text-sm"/></label><button disabled={busy} className="justify-self-start rounded bg-indigo-600 px-3 py-2 text-sm text-white disabled:opacity-50">{busy?'Saving…':'Save profile'}</button><p className="text-xs text-[var(--muted-foreground)]">Roles, management grants and departments remain under Super Admin Access Control.</p></form></details>;
}
