"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {toast} from 'sonner';
const field='rounded-lg border border-[var(--panel-border)] bg-[var(--panel)] px-3 py-2 text-sm';
export function AssignTask({userId,departmentId}:{userId:string;departmentId:string|null}){
 const [busy,setBusy]=useState(false);const router=useRouter();
 return <details className="rounded-lg border border-[var(--panel-border)] p-3"><summary className="cursor-pointer text-sm font-semibold">Assign a task</summary><form className="mt-3 grid gap-2 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=new FormData(form);body.set('assigneeId',userId);if(departmentId)body.set('departmentId',departmentId);setBusy(true);try{const res=await fetch('/api/dashboard/assignments',{method:'POST',body});const data=await res.json();if(!res.ok)throw new Error(data.message);toast.success(data.message);form.reset();router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Unable to assign.');}finally{setBusy(false);}}}>
 <input name="taskTitle" className={field} minLength={3} maxLength={300} placeholder="Task title" aria-label="Task title" required/><select className={field} name="priority" aria-label="Priority"><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option><option value="low">Low</option></select><textarea name="note" className={`${field} sm:col-span-2`} aria-label="Task description" placeholder="Task description"/><button disabled={busy||!departmentId} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{busy?'Assigning…':'Assign task'}</button>{!departmentId&&<p className="text-xs text-amber-600">Assign a department to this employee first.</p>}</form></details>;
}
export function TaskManagementActions({task,canEdit,canReopen}:{task:{id:string;taskTitle:string;taskDescription:string|null;priority:string;updatedAt:string;completed:boolean};canEdit:boolean;canReopen:boolean}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false);const router=useRouter();if(!canEdit&&!canReopen)return null;
 return <div><button className="text-xs font-medium text-indigo-500" onClick={()=>setOpen(!open)}>{task.completed?'Reopen':'Edit details'}</button>{open&&<form className="mt-2 grid gap-2" onSubmit={async e=>{e.preventDefault();const values=new FormData(e.currentTarget);setBusy(true);try{const body=task.completed?{reason:values.get('reason')}:{title:values.get('title'),description:values.get('description'),priority:values.get('priority'),reason:values.get('reason'),updatedAt:task.updatedAt};const res=await fetch('/api/management/tasks/'+task.id,{method:task.completed?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(result.message);toast.success(result.message);setOpen(false);router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Task update failed.');}finally{setBusy(false);}}}>
 {!task.completed&&<><input aria-label="Task title" name="title" className={field} defaultValue={task.taskTitle} required/><textarea aria-label="Description" name="description" className={field} defaultValue={task.taskDescription??''}/><select aria-label="Priority" name="priority" className={field} defaultValue={task.priority}>{['low','normal','high','critical'].map(p=><option key={p}>{p}</option>)}</select></>}
 <input aria-label="Reason" name="reason" placeholder="Required reason (at least 10 characters)" minLength={10} maxLength={500} required className={field}/><button disabled={busy||(task.completed?!canReopen:!canEdit)} className="rounded-lg bg-indigo-600 p-2 text-xs text-white">{busy?'Saving…':task.completed?'Reopen task':'Save details'}</button></form>}</div>;
}
type Interval={id?:string;startedAt:string;endedAt:string|null};
export function AttendanceCorrection({record}:{record:{id:string;updatedAt:string;legacyBreakMinutes:number;workSessions:Interval[];breakSessions:Interval[]}}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false);const router=useRouter();
 const toLocal=(s:string|null)=>s?new Date(new Date(s).getTime()+6*3600000).toISOString().slice(0,16):'';
 const [work,setWork]=useState(record.workSessions.map(s=>({...s,startedAt:toLocal(s.startedAt),endedAt:toLocal(s.endedAt)}))),[breaks,setBreaks]=useState(record.breakSessions.map(s=>({...s,startedAt:toLocal(s.startedAt),endedAt:toLocal(s.endedAt)})));
 const [reason,setReason]=useState('');
 if(record.workSessions.some(s=>!s.endedAt))return <p className="text-xs text-[var(--muted-foreground)]">Check out before correcting sessions.</p>;
 return <div className="mt-3"><button className="text-sm font-semibold text-indigo-500" onClick={()=>setOpen(!open)}>Correct attendance</button>{open&&<form className="mt-3 space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const map=(s:{id?:string;startedAt:string;endedAt:string})=>({...s,startedAt:s.startedAt+':00+06:00',endedAt:s.endedAt+':00+06:00'});const res=await fetch('/api/management/attendance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({recordId:record.id,updatedAt:record.updatedAt,legacyBreakMinutes:record.legacyBreakMinutes,reason,workSessions:work.map(map),breakSessions:breaks.map(map)})});const data=await res.json();if(!res.ok)throw new Error(data.message);toast.success(data.message);setOpen(false);router.refresh();}catch(e){toast.error(e instanceof Error?e.message:'Correction failed.');}finally{setBusy(false);}}}>
 <p className="text-xs text-[var(--muted-foreground)]">Times are Asia/Dhaka. Original sessions and the correction reason are preserved in the audit log.</p>
 {(['work','break'] as const).map(kind=>{const list=kind==='work'?work:breaks;const set=kind==='work'?setWork:setBreaks;return <fieldset key={kind} className="space-y-2"><legend className="text-sm font-semibold">{kind==='work'?'Office sessions':'Break sessions'}</legend>{list.map((s,i)=><div key={s.id??i} className="flex flex-wrap gap-2"><input type="datetime-local" aria-label={`${kind} start ${i+1}`} className={field} value={s.startedAt} required onChange={e=>set(prev=>prev.map((v,j)=>j===i?{...v,startedAt:e.target.value}:v))}/><input type="datetime-local" aria-label={`${kind} end ${i+1}`} className={field} value={s.endedAt} required onChange={e=>set(prev=>prev.map((v,j)=>j===i?{...v,endedAt:e.target.value}:v))}/></div>)}<button className="text-xs text-indigo-500" type="button" onClick={()=>set(prev=>[...prev,{startedAt:'',endedAt:''}])}>+ Add missing {kind} session</button></fieldset>;})}
 <textarea aria-label="Correction reason" className={`${field} w-full`} minLength={10} maxLength={1000} required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why this correction is necessary"/><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{busy?'Saving…':'Save correction'}</button></form>}</div>;
}
