'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Users,UserCheck,ClipboardList,CheckCircle2,LoaderCircle,Clock3,TriangleAlert,Filter,RotateCcw,Download,CalendarDays,Radio,Building2,ChartColumnIncreasing,ChevronLeft,ChevronRight} from 'lucide-react';
import type {ManagementDashboardData} from '@/lib/management/dashboard-data';
import styles from './management-dashboard.module.css';
const minutes=(n:number)=>`${Math.floor(n/60)}h ${String(n%60).padStart(2,'0')}m`;
const statusLabel=(s:string)=>s==='done'?'Completed':s==='in_progress'?'In progress':'Pending';
const dateTime=(s:string|null)=>s?new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(s)):'—';
const initials=(name:string)=>name.split(' ').slice(0,2).map(s=>s[0]).join('');
function Meter({value}:{value:number|null}){return <div className={styles.meterRow}><div className={styles.meter}><span style={{width:`${value??0}%`}}/></div><span>{value===null?'—':`${value}%`}</span></div>;}
export function ManagementDashboard({initial,filters}:{initial:ManagementDashboardData;filters:Record<string,string|undefined>}){
 const [data,setData]=useState(initial),[error,setError]=useState(''),[page,setPage]=useState(1),[allPeople,setAllPeople]=useState(false),[allLive,setAllLive]=useState(false),[allDepartments,setAllDepartments]=useState(false),[sort,setSort]=useState('latest');
 useEffect(()=>{const controller=new AbortController();let pending=false;const refresh=async()=>{if(document.hidden||pending)return;pending=true;try{const r=await fetch(`/api/management/dashboard${window.location.search}`,{cache:'no-store',signal:controller.signal});const next=await r.json();if(!r.ok){if(r.status===401||r.status===403){window.location.reload();return;}throw new Error(next.message??'Dashboard refresh failed.');}setData(next);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to refresh.');}finally{pending=false;}};const interval=window.setInterval(()=>void refresh(),20000);window.addEventListener('focus',refresh);return()=>{controller.abort();clearInterval(interval);window.removeEventListener('focus',refresh);};},[]);
 const rows=useMemo(()=>[...data.taskRows].sort((a,b)=>sort==='deadline'?(a.deadline??'9999').localeCompare(b.deadline??'9999'):sort==='employee'?a.employee.localeCompare(b.employee):b.lastUpdate.localeCompare(a.lastUpdate)),[data.taskRows,sort]);
 const pages=Math.max(1,Math.ceil(rows.length/10)),currentPage=Math.min(page,pages),visibleRows=rows.slice((currentPage-1)*10,currentPage*10);
 const exportQuery=new URLSearchParams(Object.entries(filters).filter((p):p is [string,string]=>typeof p[1]==='string'));exportQuery.delete('format');
 const kpis=[{label:'Total employees',value:data.kpis.employees,sub:'Within your access scope',icon:Users,tone:'blue'},
 {label:'Present in period',value:data.attendanceAccess?data.kpis.present:null,sub:data.attendanceAccess?`${data.kpis.employees?Math.round(data.kpis.present/data.kpis.employees*100):0}% checked in`:'Access not granted',icon:UserCheck,tone:'green'},
 {label:'Tasks in period',value:data.taskAccess?data.kpis.tasks:null,sub:'Includes unfinished carry-forward',icon:ClipboardList,tone:'purple'},
 {label:'Completed',value:data.taskAccess?data.kpis.completed:null,sub:`${data.kpis.tasks?Math.round(data.kpis.completed/data.kpis.tasks*100):0}% completion`,icon:CheckCircle2,tone:'green'},
 {label:'In progress',value:data.taskAccess?data.kpis.inProgress:null,sub:'Running or paused work',icon:LoaderCircle,tone:'blue'},
 {label:'Pending',value:data.taskAccess?data.kpis.pending:null,sub:'Not started',icon:Clock3,tone:'orange'},
 {label:'Overdue',value:data.taskAccess?data.kpis.overdue:null,sub:'Unfinished past deadline',icon:TriangleAlert,tone:'red'}];
 const percent=data.kpis.employees?Math.round(data.attendance.present/data.kpis.employees*100):0;
 const attentionLink=(value:string)=>{const q=new URLSearchParams(exportQuery);q.set('attention',value);return `/management?${q}`;};
 return <div className={styles.dashboard} data-management-dashboard><header className={styles.heading}><div><h1>Management Dashboard</h1><p><CalendarDays size={13}/>{data.from===data.to?data.from:`${data.from} — ${data.to}`}<span>Employee work, progress and attendance</span></p></div><div className={styles.sync} role="status">{error?<span className={styles.error}>Refresh unavailable · showing last successful data</span>:<>Updated {new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(data.generatedAt))} · refreshes every 20s</>}</div></header>
 <form className={styles.filters} action="/management"><label>Employee<select name="userId" defaultValue={filters.userId??''}><option value="">All employees</option>{data.options.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Department<select name="departmentId" defaultValue={filters.departmentId??''}><option value="">All departments</option>{data.options.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>From<input type="date" name="from" defaultValue={data.from} required/></label><label>To<input type="date" name="to" defaultValue={data.to} required/></label><label>Status<select name="taskStatus" defaultValue={filters.taskStatus??''}><option value="">All status</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="done">Completed</option></select></label><label>Priority<select name="priority" defaultValue={filters.priority??''}><option value="">All priority</option><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select></label><label className={styles.search}>Search<input name="q" placeholder="Task, employee, project…" defaultValue={filters.q??''}/></label><Link href="/management" className={styles.secondary}><RotateCcw size={13}/>Reset</Link><button className={styles.primary}><Filter size={13}/>Apply filters</button></form>
 {filters.attention&&<p className={styles.filterNote}>Showing {filters.attention} tasks. <Link href={`/management?${new URLSearchParams([...exportQuery].filter(([key])=>key!=='attention'))}`}>Clear attention filter</Link></p>}
 <div className={styles.kpis}>{kpis.map(k=><section className={styles.kpi} key={k.label}><div className={`${styles.icon} ${styles[k.tone]}`}><k.icon size={24}/></div><div><h2>{k.label}</h2><strong>{k.value??'—'}</strong><p>{k.value===null?'Access not granted':k.sub}</p></div></section>)}</div>
 <section className={styles.attention} aria-label="Requires attention"><div className={styles.attentionTitle}><TriangleAlert size={25}/><div><h2>Requires Attention</h2><p>Items to review, not automatic deductions</p></div></div><Link href={attentionLink('overdue')}><ClipboardList size={23}/><span><b>{data.taskAccess?data.kpis.overdue:'—'}</b>Overdue tasks</span><span>»</span></Link><Link href={attentionLink('urgent')}><Clock3 size={23}/><span><b>{data.taskAccess?data.attention.urgent:'—'}</b>Due within 24 hours</span><span>»</span></Link><a href="#attendance-summary"><UserCheck size={23}/><span><b>{data.attendanceAccess?data.attention.extraBreak:'—'}</b>Employees with excess break</span><span>»</span></a><a href="#live-team"><Radio size={23}/><span><b>{data.attendanceAccess?data.attention.stale:'—'}</b>Connection not confirmed</span><span>»</span></a></section>
 <div className={styles.layout}><div className={styles.main}><section className={styles.panel}><div className={styles.panelHeading}><div><h2><ClipboardList size={17}/>Tasks in selected period</h2><p>All tasks within your scope. Task time is independent of attendance.</p></div><div className={styles.actions}><select aria-label="Sort tasks" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="latest">Latest update</option><option value="deadline">Deadline</option><option value="employee">Employee</option></select>{data.canExport&&<details className={styles.export}><summary><Download size={13}/>Export</summary><div><a href={`/api/management/dashboard/export?${exportQuery}&format=xlsx`}>Excel (.xlsx)</a><a href={`/api/management/dashboard/export?${exportQuery}&format=pdf`}>PDF</a></div></details>}</div></div>
 <div className={styles.tableWrap}><table className={styles.tasks}><thead><tr>{['SL','Task','Project / Client','Assigned to','Priority','Deadline','Status','Progress','Est. time','Saved time','Last update','Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visibleRows.map((t,i)=><tr key={t.id}><td>{(currentPage-1)*10+i+1}</td><td><Link href={`/dashboard/tasks/${t.id}`} title={t.description} className={styles.taskTitle}>{t.title}</Link></td><td title={[t.project,t.client].filter(Boolean).join(' / ')}>{t.project??'—'}{t.client&&<small>{t.client}</small>}</td><td><Link className={styles.person} href={`/management/employees/${t.userId}`}><span className={styles.avatar}>{initials(t.employee)}</span>{t.employee}</Link></td><td><span className={`${styles.badge} ${styles[t.priority==='critical'?'red':t.priority==='high'?'orange':t.priority==='low'?'green':'blue']}`}>{t.priority}</span></td><td className={t.deadlineState==='overdue'?styles.error:''}>{dateTime(t.deadline)}</td><td><span className={`${styles.badge} ${styles[t.status==='done'?'green':t.status==='in_progress'?'blue':'orange']}`}>{statusLabel(t.status)}</span>{t.deadlineState==='overdue'&&<small className={styles.error}>Overdue</small>}</td><td>{t.progress===null?<span className={styles.muted}>—</span>:<Meter value={t.progress}/>} {!!t.checklistTotal&&<small>{t.checklistDone}/{t.checklistTotal} items{t.progress===100&&t.status!=='done'?' · Awaiting Done':''}</small>}</td><td>{t.estimatedMinutes===null?'—':minutes(t.estimatedMinutes)}</td><td className={styles.mono}>{minutes(t.trackedMinutes)}</td><td>{dateTime(t.lastUpdate)}</td><td><Link className={styles.textLink} href={`/dashboard/tasks/${t.id}`}>Details</Link>{t.canPlan&&t.status!=='done'&&<Link className={styles.textLink} href={`/dashboard/tasks/${t.id}/planning`}>Plan</Link>}</td></tr>)}</tbody></table>{!visibleRows.length&&<p className={styles.empty}>{data.taskAccess?'No tasks match these filters.':'Task view access has not been granted.'}</p>}</div>
 <div className={styles.tableFooter}><span>Showing {rows.length?(currentPage-1)*10+1:0}–{Math.min(currentPage*10,rows.length)} of {rows.length} tasks</span><div><button type="button" aria-label="Previous task page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={15}/></button><span>{currentPage} / {pages}</span><button type="button" aria-label="Next task page" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={15}/></button></div></div></section>
 <div className={styles.summaries}><section className={styles.panel}><div className={styles.panelHeading}><h2><Users size={16}/>Employee summary</h2><button type="button" onClick={()=>setAllPeople(!allPeople)}>{allPeople?'Show less':'View all'}</button></div><div className={styles.tableWrap}><table><thead><tr>{['Employee','Department','Tasks','Done','Pending','Task time','Completion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(allPeople?data.employees:data.employees.slice(0,5)).map(e=><tr key={e.id}><td><Link href={`/management/employees/${e.id}`}>{e.name}</Link></td><td>{e.department}</td><td>{data.taskAccess?e.assigned:'—'}</td><td>{data.taskAccess?e.completed:'—'}</td><td>{data.taskAccess?e.pending:'—'}</td><td>{data.taskAccess?minutes(e.trackedMinutes):'—'}</td><td><Meter value={data.taskAccess?e.completionRate:null}/></td></tr>)}</tbody></table></div></section>
 <section className={styles.panel}><div className={styles.panelHeading}><h2><Building2 size={16}/>Department summary</h2><button type="button" onClick={()=>setAllDepartments(!allDepartments)}>{allDepartments?'Show less':'View all'}</button></div><div className={styles.tableWrap}><table><thead><tr>{['Department','People','Done','Pending','Completion'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{(allDepartments?data.departments:data.departments.slice(0,5)).map(d=><tr key={d.id}><td>{d.name}</td><td>{d.employees}</td><td>{data.taskAccess?d.completed:'—'}</td><td>{data.taskAccess?d.pending:'—'}</td><td><Meter value={data.taskAccess?d.completionRate:null}/></td></tr>)}</tbody></table></div></section>
 <section className={styles.panel}><div className={styles.panelHeading}><h2><ChartColumnIncreasing size={16}/>Weekly task status</h2></div><div className={styles.legend}><span><i className={styles.greenDot}/>Completed</span><span><i className={styles.blueDot}/>In progress</span><span><i className={styles.orangeDot}/>Pending</span></div>{data.taskAccess?<div className={styles.chart} role="img" aria-label={`Task status for the seven days ending ${data.to}`}>{data.week.map(w=>{const max=Math.max(1,...data.week.map(d=>d.completed+d.inProgress+d.pending));return <div className={styles.chartColumn} key={w.date} title={`${w.date}: ${w.completed} completed, ${w.inProgress} in progress, ${w.pending} pending`}><div className={styles.bar}><span style={{height:`${w.pending/max*100}%`,background:'#f6ab47'}}/><span style={{height:`${w.inProgress/max*100}%`,background:'#468bf2'}}/><span style={{height:`${w.completed/max*100}%`,background:'#31bd82'}}/></div><small>{w.date.slice(5)}</small></div>;})}</div>:<p className={styles.empty}>Task view access not granted.</p>}<p className={styles.chartNote}>Scope-filtered daily task states; status and priority filters apply to the main table.</p></section></div></div>
 <aside className={styles.right}><section id="live-team" className={styles.panel}><div className={styles.panelHeading}><h2><Radio size={17}/>Live team status</h2><button type="button" onClick={()=>setAllLive(!allLive)}>{allLive?'Show less':'View all'}</button></div><p className={styles.liveNote}>Today · recorded work state + connection freshness</p><div className={styles.liveTotals}>{['Task running','Available','In meeting'].map(label=><div key={label}><span>{label}</span><b>{data.attendanceAccess?data.live.filter(p=>p.state===label).length:'—'}</b></div>)}</div><div className={styles.liveList}>{(allLive?data.live:data.live.slice(0,6)).map(p=><Link className={styles.livePerson} key={p.id} href={`/management/employees/${p.id}`} title={p.tasks.join(', ')}><span className={styles.avatar}>{initials(p.name)}</span><span className={styles.liveName}>{p.name}<small>{p.connected?'Connected':`Last seen ${dateTime(p.lastSeenAt)}`}</small></span><span className={`${styles.state} ${p.connected?styles.connected:styles.disconnected}`}><i/>{p.state}</span></Link>)}</div>{!data.live.length&&<p className={styles.empty}>{data.attendanceAccess?'No employees in this scope.':'Attendance view access not granted.'}</p>}<p className={styles.chartNote}>Available is not “idle.” Connection loss does not stop or deduct attendance. Device activity monitoring is not enabled.</p></section>
 <section id="attendance-summary" className={styles.panel}><div className={styles.panelHeading}><h2><CalendarDays size={17}/>Attendance summary</h2></div>{data.attendanceAccess?<><div className={styles.attendanceBody}><div className={styles.donut} style={{background:`conic-gradient(#31b77f ${percent}%, #e7edf6 0)`}} role="img" aria-label={`${percent}% of scoped employees checked in during this period`}><span>{percent}%</span></div><dl><div><dt><i className={styles.greenDot}/>Checked in</dt><dd>{data.attendance.present}</dd></div><div><dt><i className={styles.grayDot}/>Not checked in</dt><dd>{data.attendance.notCheckedIn}</dd></div><div><dt><i className={styles.orangeDot}/>Late check-in</dt><dd>{data.attendance.late}</dd></div></dl></div><div className={styles.attendanceFoot}><span>Counted attendance <b>{minutes(data.attendance.countedMinutes)}</b></span><span>Excess break <b>{minutes(data.attendance.excessBreakMinutes)}</b></span></div><p className={styles.chartNote}>Late is a subset of checked-in employees. No leave/absence assumption is made.</p></>:<p className={styles.empty}>Attendance view access not granted.</p>}</section></aside></div>
 </div>;
}
