import { formatDateInDhaka } from "@/lib/utils";
import { DateInput } from "@/components/ui/date-input";
import Link from 'next/link';
import {db} from '@/lib/db';
import {getReadableTaskDescription} from '@/lib/report-summary';
import {formatMinutes,toDateOnly} from '@/lib/utils';
import type {Prisma} from '@prisma/client';
export async function PermanentHistory({userId,search}:{userId:string;search:{from?:string;to?:string;page?:string}}){
 const valid=(s?:string)=>s&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(new Date(s).getTime())?s:undefined;
 const from=valid(search.from),to=valid(search.to);if(from&&to&&from>to)return <p>Choose a start date before the end date.</p>;
 const range={...(from?{gte:new Date(from)}:{}),...(to?{lte:new Date(to)}:{})};
 const where:Prisma.DailyTaskWhereInput={userId,OR:[{activityEvents:{some:{eventType:'completed',...(from||to?{reportDate:range}:{})}}},{updates:{some:{status:'done',...(from||to?{reportDate:range}:{})}}}]};
 const count=await db.dailyTask.count({where});const pages=Math.max(1,Math.ceil(count/20)),page=Math.min(pages,Math.max(1,Math.floor(Number(search.page)||1)));
 const tasks=await db.dailyTask.findMany({where,include:{updates:{orderBy:{reportDate:'desc'}},department:{select:{name:true}}},orderBy:[{updatedAt:'desc'},{id:'desc'}],skip:(page-1)*20,take:20});
 const query=new URLSearchParams({...(from?{from}:{}),...(to?{to}:{})});
 return <div className="space-y-4"><h1 className="text-2xl font-semibold">My History</h1><p className="text-sm text-[var(--muted-foreground)]">Permanent, read-only task records. Reopening a task keeps its previous completion history.</p><form className="flex flex-wrap items-end gap-3 text-sm"><label>From<DateInput aria-label="History from date" name="from" defaultValue={from} className="ml-2 rounded border bg-[var(--panel)] p-2"/></label><label>To<DateInput aria-label="History to date" name="to" defaultValue={to} max={toDateOnly()} className="ml-2 rounded border bg-[var(--panel)] p-2"/></label><button className="rounded-lg bg-indigo-600 px-4 py-2 text-white">Filter</button><Link className="px-3 py-2 text-indigo-500" href="/dashboard/history">All dates</Link></form><section className="rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-4"><h2 className="font-semibold">Work History · {count} records</h2>{tasks.map(t=><article className="mt-3 flex flex-col justify-between gap-3 border-t border-[var(--panel-border)] pt-4 sm:flex-row" key={t.id}><div className="min-w-0"><h3 className="text-sm font-semibold">{t.taskTitle}</h3><p className="mt-1 line-clamp-2 text-xs text-[var(--muted-foreground)]">{getReadableTaskDescription(t.taskDescription)}</p><p className="mt-2 text-xs">{t.department.name} · Planned {formatDateInDhaka(t.planDate)} · {formatMinutes(t.updates.reduce((n,u)=>n+u.trackedMinutes,0))} · {t.updates[0]?.status==='done'?'Completed':'Reopened'}</p></div><Link className="self-start rounded-full border border-[var(--panel-border)] px-4 py-1.5 text-xs font-medium text-indigo-500" href={`/dashboard/tasks/${t.id}`}>Details</Link></article>)}{!tasks.length&&<p className="py-10 text-center text-sm text-[var(--muted-foreground)]">No completed task records in this range.</p>}<div className="mt-5 flex items-center justify-end gap-4 text-sm">{page>1&&<Link href={`?${query}&page=${page-1}`}>← Previous</Link>}<span>{page} / {pages}</span>{page<pages&&<Link href={`?${query}&page=${page+1}`}>Next →</Link>}</div></section></div>;
}
