import Link from 'next/link';
import {roleUiTitle} from '@/lib/auth/roles';
import {formatMinutes,formatDateTimeInDhaka} from '@/lib/utils';
import type {managementRecords} from '@/lib/management/records';
const panel='rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-4';
export function RecordsView({data,report=false,canExport=false}:{data:Awaited<ReturnType<typeof managementRecords>>;report?:boolean;canExport?:boolean}){
 const sum=(key:'completed'|'tracked'|'counted'|'overtime')=>data.rows.reduce((n,r)=>n+(r[key]??0),0);
 const totals=[['People in scope',data.rows.length],...(data.attendanceAllowed?[['Working now',data.rows.filter(r=>r.state==='Working').length],['On break',data.rows.filter(r=>r.state==='On break').length],['Counted work',formatMinutes(sum('counted'))],['Overtime',formatMinutes(sum('overtime'))]]:[]),...(data.tasksAllowed?[['Completed tasks',sum('completed')],['Task time',formatMinutes(sum('tracked'))]]:[])];
 const query=`from=${data.from}&to=${data.to}`;
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{totals.map(([label,value])=><div className={panel} key={label}><p className="text-xs uppercase tracking-wide text-[var(--muted-foreground)]">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p></div>)}</div>
 {report&&canExport&&<div className="flex gap-3"><Link className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white" href={`/api/management/reports/export?${query}&format=xlsx`}>Download Excel</Link><Link className="rounded-lg border border-[var(--panel-border)] px-4 py-2 text-sm" href={`/api/management/reports/export?${query}&format=pdf`}>Download PDF</Link></div>}
 <section className={panel}><h2 className="mb-3 font-semibold">Employee records <span className="text-sm text-[var(--muted-foreground)]">· {data.rows.length}</span></h2><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-[var(--panel-alt)] text-xs uppercase text-[var(--muted-foreground)]"><tr>{['Employee','Role / Team',...(data.attendanceAllowed?['Attendance','In / Out','Active / Counted','Break / Outside','Overtime']:[]),...(data.tasksAllowed?['Tasks','Task time']:[]),'Details'].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t border-[var(--panel-border)] hover:bg-[var(--panel-alt)]"><td className="p-3 font-medium">{r.name}<span className="block font-mono text-[10px] text-[var(--muted-foreground)]">{r.id.slice(0,8)}</span></td><td className="p-3">{roleUiTitle(r.role)}<span className="block text-xs text-[var(--muted-foreground)]">{r.department?.name??'No department'} · {r.team?.name??'No team'}</span></td>{data.attendanceAllowed&&<><td className="p-3"><span className="rounded-full bg-indigo-500/10 px-2 py-1 text-xs">{r.state}</span></td><td className="p-3 text-xs">{r.firstIn?formatDateTimeInDhaka(r.firstIn):'—'}<span className="block">{r.lastOut?formatDateTimeInDhaka(r.lastOut):'—'}</span></td><td className="p-3">{formatMinutes(r.actual??0)} / {formatMinutes(r.counted??0)}</td><td className="p-3">{formatMinutes(r.break??0)} / {formatMinutes(r.outside??0)}</td><td className="p-3">{formatMinutes(r.overtime??0)}</td></>}{data.tasksAllowed&&<><td className="p-3">{r.completed}/{r.planned} done<span className="block text-xs text-[var(--muted-foreground)]">{r.pending} pending · {r.inProgress} in progress</span></td><td className="p-3">{formatMinutes(r.tracked??0)}</td></>}<td className="p-3"><Link href={`/management/employees/${r.id}?${query}`} className="font-medium text-indigo-500">View details</Link></td></tr>)}</tbody></table>{!data.rows.length&&<p className="p-8 text-center text-[var(--muted-foreground)]">No employees match this access scope and filter.</p>}</div></section>
 {!report&&<section className={panel}><h2 className="font-semibold">Attention required</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">Attendance observations, not absence or payroll decisions. Task timers may overlap.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{data.rows.filter(r=>r.flags.length).slice(0,30).map(r=><Link key={r.id} href={`/management/employees/${r.id}?${query}`} className="rounded-lg bg-[var(--panel-alt)] p-3 text-sm"><span className="font-medium">{r.name}</span><span className="mt-1 block text-xs text-[var(--muted-foreground)]">{r.flags.join(' · ')}</span></Link>)}</div></section>}
 </div>;
}
