'use client';
import { DateTimeInput } from "@/components/ui/date-time-input";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {toast} from 'sonner';
import type {ChecklistItem} from '@/lib/management/task-insights';
import {taskProgress} from '@/lib/management/task-insights';
import {createId} from '@/lib/utils';
type Plan={id:string;title:string;version:number;projectName:string|null;clientName:string|null;dueAt:string|null;estimatedMinutes:number|null;checklist:ChecklistItem[];status:string};
export function TaskPlanningEditor({plan,canPlan,management}:{plan:Plan;canPlan:boolean;management:boolean}){
 const router=useRouter();const [items,setItems]=useState(plan.checklist),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const finished=plan.status==='done',percent=taskProgress(plan.status,items);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(event.currentTarget);
  try{const localDue=String(form.get('dueAt')??'');const response=await fetch(`/api/dashboard/tasks/${plan.id}/planning`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:plan.version,projectName:canPlan?String(form.get('projectName')??'').trim()||null:plan.projectName,clientName:canPlan?String(form.get('clientName')??'').trim()||null:plan.clientName,dueAt:canPlan?(localDue?new Date(localDue+'+06:00').toISOString():null):plan.dueAt,estimatedMinutes:canPlan?(form.get('estimate')?Number(form.get('estimate')):null):plan.estimatedMinutes,checklist:items,reason:String(form.get('reason')??'')})});const data=await response.json();if(!response.ok)throw new Error(data.message??'Could not save.');toast.success(data.message);router.refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save planning details.');}finally{setBusy(false);}}
 const input='mt-1 w-full rounded-lg border border-[var(--panel-border)] bg-[var(--panel)] px-3 py-2 text-sm disabled:opacity-60';
 const due=plan.dueAt?new Date(new Date(plan.dueAt).getTime()+21600000).toISOString().slice(0,16):'';
 return <form onSubmit={save} className="mx-auto w-full max-w-3xl space-y-5 rounded-2xl border border-[var(--panel-border)] bg-[var(--panel)] p-5"><div><Link href={`/dashboard/tasks/${plan.id}`} className="text-xs text-indigo-600">Read-only task details →</Link><h1 className="mt-2 text-xl font-semibold">{plan.title}</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">Planning & checklist · {percent===null?'No checklist percentage':`${percent}% checklist completion`}</p></div>
 <fieldset disabled={!canPlan||finished||busy} className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Project<input name="projectName" maxLength={120} defaultValue={plan.projectName??''} className={input}/></label><label className="text-xs">Client<input name="clientName" maxLength={120} defaultValue={plan.clientName??''} className={input}/></label><label className="text-xs">Deadline (Dhaka time)<DateTimeInput name="dueAt" defaultValue={due} className={input}/></label><label className="text-xs">Estimated time (minutes)<input name="estimate" type="number" min={1} max={525600} defaultValue={plan.estimatedMinutes??''} className={input}/></label></fieldset>
 <section><h2 className="font-semibold">Checklist / subtasks</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">All items must be checked before Done. Completing the checklist does not automatically finish the task.</p><div className="mt-3 space-y-2">{items.map((item,index)=><div key={item.id} className="flex items-center gap-2"><input aria-label={`Complete ${item.title||`item ${index+1}`}`} type="checkbox" checked={item.done} disabled={finished||busy} onChange={e=>setItems(items.map(i=>i.id===item.id?{...i,done:e.target.checked}:i))}/><input aria-label={`Checklist item ${index+1}`} maxLength={200} required value={item.title} disabled={!canPlan||finished||busy} className={input+' !mt-0'} onChange={e=>setItems(items.map(i=>i.id===item.id?{...i,title:e.target.value}:i))}/>{canPlan&&!finished&&<button type="button" disabled={busy} aria-label={`Remove item ${index+1}`} onClick={()=>setItems(items.filter(i=>i.id!==item.id))} className="p-2 text-rose-600">×</button>}</div>)}</div>{canPlan&&!finished&&items.length<50&&<button type="button" disabled={busy} className="mt-3 text-sm text-indigo-600" onClick={()=>setItems([...items,{id:createId(),title:'',done:false}])}>+ Add checklist item</button>}{!items.length&&<p className="mt-2 text-sm text-[var(--muted-foreground)]">Optional. No percentage is fabricated when there is no checklist.</p>}</section>
 {management&&!finished&&<label className="block text-xs">Reason for change<textarea name="reason" required minLength={10} maxLength={1000} className={input}/></label>}{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex items-center justify-between"><Link href={management?'/management':'/dashboard'} className="text-sm text-[var(--muted-foreground)]">Back</Link>{!finished&&<button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?'Saving…':'Save planning'}</button>}</div>
 </form>;
}
