import {db} from '@/lib/db';
import {readChecklist} from '@/lib/management/task-insights';
import {employeeScope,type AccessActor} from '@/lib/auth/policy';
import {notFound} from 'next/navigation';
import {getReadableTaskDescription} from '@/lib/report-summary';
import {formatDateTimeInDhaka,formatMinutes} from '@/lib/utils';
export async function TaskRecord({actor,taskId}:{actor:AccessActor;taskId:string}){
 const task=await db.dailyTask.findFirst({where:{id:taskId,OR:[{userId:actor.id},{user:employeeScope(actor,'tasks.view')},{user:employeeScope(actor,'history.view')}]},include:{user:{select:{name:true}},department:{select:{name:true}},assigner:{select:{name:true}},updates:{orderBy:{reportDate:'asc'}},activityEvents:{include:{actor:{select:{name:true}}},orderBy:{createdAt:'asc'}},timelineEntries:{orderBy:{createdAt:'asc'}}}});
 if(!task)notFound();
 const fmt=(d:Date|null)=>d?formatDateTimeInDhaka(d):'—';
 const card='rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-5';
 return <div className="space-y-4"><section className={card}><p className="text-xs font-medium uppercase tracking-wide text-indigo-500">Read-only task record</p><h1 className="mt-2 text-2xl font-semibold">{task.taskTitle}</h1><p className="mt-3 whitespace-pre-wrap text-sm text-[var(--muted-foreground)]">{getReadableTaskDescription(task.taskDescription)}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">{[['Owner',task.user.name],['Department',task.department.name],['Assigned by',task.assigner?.name??'Self'],['Project',task.projectName??'Not set'],['Client',task.clientName??'Not set'],['Deadline',fmt(task.dueAt)],['Estimated time',task.estimatedMinutes?formatMinutes(task.estimatedMinutes):'Not set'],['Priority',task.priority],['Planned date',task.planDate.toISOString().slice(0,10)],['Created',fmt(task.createdAt)],['Current status',task.updates.at(-1)?.status??'pending'],['Tracked time',formatMinutes(task.updates.reduce((n,u)=>n+u.trackedMinutes,0))],['Task ID',task.id]].map(([label,value])=><div key={label}><dt className="text-xs text-[var(--muted-foreground)]">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl></section>
 <section className={card}><h2 className="font-semibold">Checklist / subtasks</h2>{readChecklist(task.checklist).length?readChecklist(task.checklist).map(item=><p key={item.id} className="mt-2 text-sm">{item.done?'?':'?'} {item.title}</p>):<p className="mt-2 text-sm text-[var(--muted-foreground)]">No checklist added.</p>}</section>
 <section className={card}><h2 className="font-semibold">Daily work records</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Date','Status','Start','End / pause','Time','Note'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{task.updates.map(u=><tr className="border-t border-[var(--panel-border)]" key={u.id}><td className="p-2">{u.reportDate.toISOString().slice(0,10)}</td><td className="p-2">{u.status==='done'?'Completed (100%)':u.status}</td><td className="p-2">{fmt(u.actualStart)}</td><td className="p-2">{fmt(u.actualEnd)}</td><td className="p-2">{formatMinutes(u.trackedMinutes)}</td><td className="min-w-48 whitespace-pre-wrap p-2">{u.note??'—'}</td></tr>)}</tbody></table></div></section>
 <section className={card}><h2 className="font-semibold">Completion and reopen history</h2>{task.activityEvents.map(e=><article key={e.id} className="mt-3 border-l-2 border-indigo-400 py-1 pl-4"><p className="text-sm font-semibold">{e.eventType==='completed'?'Completed':'Reopened'} · Cycle {e.cycle}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{fmt(e.createdAt)} · {e.actor?.name??'System'} · {formatMinutes(e.trackedMinutes)}</p><p className="mt-2 whitespace-pre-wrap text-sm">{e.reason??e.note??'No additional note'}</p></article>)}{!task.activityEvents.length&&<p className="mt-3 text-sm text-[var(--muted-foreground)]">No recorded completion events. Older task evidence remains in daily records above.</p>}</section>
 <section className={card}><h2 className="font-semibold">Activity timeline</h2><p className="mt-1 text-xs text-[var(--muted-foreground)]">Detailed events are recorded from the management upgrade onwards; older events are shown only where evidence exists.</p>{task.timelineEntries.map(e=><details key={e.id} className="mt-3 border-t border-[var(--panel-border)] pt-3"><summary className="cursor-pointer text-sm">{e.eventType.replaceAll('_',' ')} · {fmt(e.createdAt)}</summary><p className="mt-2 whitespace-pre-wrap text-sm">{e.note}</p>{e.snapshot&&<pre className="mt-2 overflow-auto rounded bg-[var(--panel-alt)] p-3 text-xs">{JSON.stringify(e.snapshot,null,2)}</pre>}</details>)}</section></div>;
}
