import Link from 'next/link';
import {db} from '@/lib/db';
import {can,ownTeamScope,type AccessActor} from '@/lib/auth/policy';
import {roleUiTitle} from '@/lib/auth/roles';
export async function TeamWorkspace({actor}:{actor:AccessActor}){
 const members=await db.user.findMany({where:ownTeamScope(actor),select:{id:true,name:true,role:true,designation:true,isActive:true,team:{select:{name:true}}},orderBy:{name:'asc'}});
 const assigned=await db.dailyTask.findMany({where:{assignedBy:actor.id,user:ownTeamScope(actor)},include:{user:{select:{name:true}},updates:{orderBy:{reportDate:'desc'},take:1}},orderBy:{createdAt:'desc'},take:100});
 return <div className="space-y-4"><h1 className="text-2xl font-semibold">My Team</h1><p className="text-sm text-[var(--muted-foreground)]">Team membership and assignments. Super Admin controls management and write permissions.</p><section className="rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-4"><h2 className="font-semibold">Team members</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{members.map(m=><div key={m.id} className="rounded-lg bg-[var(--panel-alt)] p-3 text-sm"><p className="font-semibold">{m.name}</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{roleUiTitle(m.role)} · {m.team?.name??'No team'} · {m.isActive?'Active':'Inactive'}</p>{can(actor,'employees.view')&&<Link className="mt-2 inline-block text-xs text-indigo-500" href={`/management/employees/${m.id}`}>Management details →</Link>}</div>)}</div>{!members.length&&<p className="mt-3 text-sm">No team has been assigned. Super Admin can set up your team in Access Control.</p>}</section><section className="rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-4"><h2 className="font-semibold">Assignments created by you</h2><Link className="text-sm text-indigo-500" href="/dashboard/assignments">Open assignments and reviews →</Link>{assigned.map(t=><div key={t.id} className="mt-3 border-t border-[var(--panel-border)] pt-3 text-sm">{t.taskTitle} · {t.user.name} · {t.updates[0]?.status??'pending'}</div>)}</section></div>;
}
