import Link from 'next/link';
import {EmployeeProfileEditor} from '@/components/management/employee-profile-editor';
import {notFound,redirect} from 'next/navigation';
import {requireUser} from '@/lib/auth/server';
import {can,canOpenManagement} from '@/lib/auth/policy';
import {employeeDetails} from '@/lib/management/records';
import {roleUiTitle} from '@/lib/auth/roles';
import {formatMinutes,formatDateTimeInDhaka} from '@/lib/utils';
import { attendanceRevision } from "@/lib/attendance-record";
import {AssignTask,TaskManagementActions,AttendanceCorrection} from '@/components/management/employee-actions';
export default async function EmployeeDetailsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const actor=await requireUser();if(!canOpenManagement(actor))redirect('/dashboard');const {id}=await params;const search=await searchParams;
 const query=new URLSearchParams(Object.entries(search).filter((e):e is [string,string]=>typeof e[1]==='string'));
 let data;try{data=await employeeDetails(actor,id,query);}catch{notFound();}
 const employee=data.employee,tab=search.tab??'overview';const range=`from=${data.from}&to=${data.to}`;
 const tabs=[['overview','Overview'],...(data.taskAccess?[['tasks','Tasks']]:[]),...(data.attendanceAccess?[['attendance','Attendance']]:[]),...(data.historyAccess?[['history','History']]:[]),...(can(actor,'reports.view')?[['reports','Reports']]:[])];
 const card='rounded-xl border border-[var(--panel-border)] bg-[var(--panel)] p-4';
 return <div className="space-y-4"><Link href="/management" className="text-sm text-indigo-500">← Management</Link><div><h1 className="text-2xl font-semibold">{employee.name}</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">{roleUiTitle(employee.role)} · {employee.department?.name??'No department'} · {employee.team?.name??'No team'}</p></div>
 <nav className="flex flex-wrap gap-2">{tabs.map(([key,label])=><Link key={key} className={`rounded-lg px-4 py-2 text-sm ${tab===key?'bg-indigo-600 text-white':'bg-[var(--panel)]'}`} href={`?${range}&tab=${key}`}>{label}</Link>)}</nav>
 <form className="flex flex-wrap gap-2 text-sm"><input name="tab" value={tab} hidden readOnly/><label>From <input className="rounded border border-[var(--panel-border)] bg-[var(--panel)] p-2" type="date" name="from" defaultValue={data.from}/></label><label>To <input className="rounded border border-[var(--panel-border)] bg-[var(--panel)] p-2" type="date" name="to" defaultValue={data.to}/></label><button className="rounded bg-indigo-600 px-4 text-white">View</button></form>
 {tab==='overview'&&<section className={card}><h2 className="font-semibold">Employee record</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-[var(--muted-foreground)]">Employee ID</dt><dd className="break-all font-mono">{employee.id}</dd></div><div><dt className="text-[var(--muted-foreground)]">Email</dt><dd>{employee.email}</dd></div><div><dt className="text-[var(--muted-foreground)]">Designation</dt><dd>{employee.designation??'—'}</dd></div><div><dt className="text-[var(--muted-foreground)]">Account</dt><dd>{employee.isActive?'Active':'Inactive'}</dd></div></dl>{can(actor,'employees.update')&&<EmployeeProfileEditor key={employee.updatedAt.toISOString()} employee={{id:employee.id,name:employee.name,designation:employee.designation,phone:employee.phone,location:employee.location,updatedAt:employee.updatedAt.toISOString()}}/>}</section>}
 {tab==='tasks'&&data.taskAccess&&<div className="space-y-3">{can(actor,'tasks.assign')&&<AssignTask userId={id} departmentId={employee.departmentId}/>}<p className="text-xs text-[var(--muted-foreground)]">Up to 500 tasks in this view. Narrow the dates for older records.</p>{data.tasks.map(t=><section key={t.id} className={card}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{t.taskTitle}</h3><span className="text-xs">{t.updates[0]?.status??'pending'} · {t.priority}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-[var(--muted-foreground)]">{t.taskDescription}</p><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><Link href={`/dashboard/tasks/${t.id}`} className="text-sm text-indigo-500">Full task details →</Link><TaskManagementActions task={{id:t.id,taskTitle:t.taskTitle,taskDescription:t.taskDescription,priority:t.priority,updatedAt:t.updatedAt.toISOString(),completed:t.updates[0]?.status==='done'}} canEdit={can(actor,'tasks.update')} canReopen={can(actor,'tasks.reopen')}/></div></section>)}</div>}
 {tab==='attendance'&&data.attendanceAccess&&<div className="space-y-3">{data.attendance.map(r=><section key={r.id} className={card}><h3 className="font-semibold">{r.attendanceDate.toISOString().slice(0,10)}</h3><p className="mt-2 text-sm">Actual {formatMinutes(r.metrics.activeMinutes)} · Counted {formatMinutes(r.metrics.workingMinutes)} · Break {formatMinutes(r.metrics.breakMinutes)} · Outside {formatMinutes(r.metrics.outsideMinutes)} · Overtime {formatMinutes(r.metrics.overtimeMinutes)}</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{[['Office sessions',r.workSessions],['Break sessions',r.breakSessions]].map(([label,items])=><div key={label as string}><h4 className="text-sm font-medium">{label as string}</h4>{(items as typeof r.workSessions).map(s=><p key={s.id} className="mt-1 text-xs text-[var(--muted-foreground)]">{formatDateTimeInDhaka(s.startedAt)} → {s.endedAt?formatDateTimeInDhaka(s.endedAt):'Running'} · {s.endReason??'—'}</p>)}</div>)}</div>{can(actor,'attendance.correct')&&<AttendanceCorrection record={{id:r.id,revision:attendanceRevision(r),updatedAt:r.updatedAt.toISOString(),legacyBreakMinutes:r.legacyBreakMinutes,workSessions:r.workSessions.map(s=>({id:s.id,startedAt:s.startedAt.toISOString(),endedAt:s.endedAt?.toISOString()??null})),breakSessions:r.breakSessions.map(s=>({id:s.id,startedAt:s.startedAt.toISOString(),endedAt:s.endedAt?.toISOString()??null}))}}/>}</section>)}{!data.attendance.length&&<p className={card}>No attendance in this date range.</p>}</div>}
 {tab==='history'&&data.historyAccess&&<section className={card}><h2 className="font-semibold">Permanent work history</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Read-only records. Completion and reopen events remain available.</p>{data.history.map(t=><div key={t.id} className="mt-3 flex justify-between gap-3 border-t border-[var(--panel-border)] pt-3 text-sm"><span>{t.taskTitle}</span><Link className="text-indigo-500" href={`/dashboard/tasks/${t.id}`}>Details</Link></div>)}</section>}
 {tab==='reports'&&can(actor,'reports.view')&&<section className={card}><Link className="text-indigo-500" href={`/management/reports?${range}&userId=${id}`}>View employee report →</Link></section>}
 </div>;
}
